### ISSUE TITLE
The icons are not visible below vh and you cannot scroll. 

### ISSUE THREAD

**Issue by SaeedMalikx** [aholachek/react-flip-toolkit-router-example#1]
I think you have inner divs with fixed position. The icons are not visible if they go below view height. I added auto scroll and max height to the inverted div for a quick fix. 

The same problem happens with your 

"Image Transition Demo"

Someone can easily attribute the error with the toolkit, which is not the case.

![cap2](https://user-images.githubusercontent.com/25725772/46586438-6aa00f80-ca4c-11e8-977e-c92686e10d8f.PNG)

![cap1](https://user-images.githubusercontent.com/25725772/46586361-7808ca00-ca4b-11e8-9bbc-1ca3602d6759.PNG)

**Comment by aholachek** [comment]
Thank you for catching this! I finally fixed it.
